sudo: required

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=server-centos-7
  - INSTANCE=server-debian-8
  - INSTANCE=server-debian-9
  - INSTANCE=server-ubuntu-1404
  - INSTANCE=server-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - /opt/chefdk/embedded/bin/chef gem install danger

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
    - script:
      - /opt/chefdk/bin/chef exec danger
      env: DANGER
